---
- name: Deploy Angular application to Frontend swarm
  hosts: frontend-manager
  gather_facts: false
  become: yes
  vars:
    fe_image_tag: "arojasqx7/frontend-gl:159"
  tasks:
   - name: Pull Angular frontend docker image
     shell: docker pull {{ fe_image_tag }}

   - name: Run image to init container
     shell: docker run -d -p 4200:4200 {{ fe_image_tag }}
   
   - name: Create Frontend service
     shell: docker service create --name frontend {{ fe_image_tag }}