---
- name: Deploy Angular application to Frontend swarm
  hosts: frontend-manager
  gather_facts: false
  become: yes
  tasks:
   - name: Pull Angular frontend docker image
     shell: docker pull arojasqx7/frontend-gl:13