---
- name: Deploy Java spring application to Backend swarm
  hosts: backend-manager
  gather_facts: false
  become: yes
  vars:
    java_image_tag:  "arojasqx7/spring-boot-realworld-example-app:latest"
    mysql_image_tag: "arojasqx7/mysql:latest"
  tasks:
   - name: Pull Spring Boot Java backend docker image
     shell: docker pull {{ java_image_tag }}

   - name: Pull MySQL db backend docker image
     shell: docker pull {{ mysql_image_tag }}
   
   - name: Create Java Backend service
     shell: docker service create --name backend {{ java_image_tag }}
   
   - name: Create DB Backend service
     shell: docker service create --name backend_db {{ mysql_image_tag }}